name: S3 Sync

# Controls when the action will run
on:
  # Triggers the workflow on push or pull request events but only for master branch
  push:
    branches:
      - master

# Allows you to run this workflow manually from the Actions tab
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: jakejarvis/s3-sync-action@v0.5.1
      with:
        args: --acl public-read --follow-symlinks --delete
      env:
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: 'us-west-2'   # optional: defaults to us-east-1
